### ISSUE TITLE
Fix blank space in maximized mode

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_kuet#60]
In some themes the space occupied by the navigation is left blank in maximized mode:

![Image](https://github.com/user-attachments/assets/ebf33403-1a55-4871-af25-ae25e6c6fb7a)

I fixed it in Moove Theme by setting "margin-top: 0px!important" in CSS rule:

```CSS
body.path-mod-kuet.fullscreen #page {
    margin-top: 0;
    padding: 0;
    height: 100vh;
    margin-top: 0px!important;
}
```

Is this secure in general? Is this worth and safe to include in Kuet?
